osm_bpf_parser: Fix check for boost library
On Ubuntu 25.04 aarch64, the test command is printing the message
"undefined reference to `main'" two times instead of one.

Fix #2515.